name: Verify

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: elves/setup-elvish@v1
        with:
          elvish-version: 0.21.0

      - shell: elvish {0}
        run: |
          use epm

          epm:install github.com/giancosta86/epm-plus

          use github.com/giancosta86/epm-plus/epm-plus

          epm-plus:patch-epm

          epm:install

      - shell: bash
        run: elvish verify.elv
